export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_RESOURCES: 'VIEW_RESOURCES',
  VIEW_MEETING_SERVICE: 'VIEW_MEETING_SERVICE',
  VIEW_APPROVAL_CENTER: 'VIEW_APPROVAL_CENTER',
  VIEW_PROFILE: 'VIEW_PROFILE',
  
  VIEW_BOOKINGS: 'VIEW_BOOKINGS',
  EDIT_PROFILE: 'EDIT_PROFILE',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  MANAGE_DEPARTMENTS: 'MANAGE_DEPARTMENTS',
  MANAGE_RESOURCES: 'MANAGE_RESOURCES',
  CONFIG_WORKFLOW: 'CONFIG_WORKFLOW',
  ACCESS_DATA_CENTER: 'ACCESS_DATA_CENTER',
  
  VIEW_ALL_BOOKINGS: 'VIEW_ALL_BOOKINGS',
  APPROVE_BOOKINGS: 'APPROVE_BOOKINGS',
  VIEW_ALL_USERS: 'VIEW_ALL_USERS',
  EDIT_ALL_USERS: 'EDIT_ALL_USERS',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  SYSTEM_ADMIN: Object.values(PERMISSIONS),
  
  APPROVAL_ADMIN: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_RESOURCES,
    PERMISSIONS.VIEW_APPROVAL_CENTER,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.EDIT_PROFILE,
    PERMISSIONS.VIEW_ALL_BOOKINGS,
    PERMISSIONS.APPROVE_BOOKINGS,
  ],
  
  MEETING_SERVICE: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_RESOURCES,
    PERMISSIONS.VIEW_MEETING_SERVICE,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.EDIT_PROFILE,
    PERMISSIONS.VIEW_ALL_BOOKINGS,
  ],
  
  EMPLOYEE: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_RESOURCES,
    PERMISSIONS.VIEW_PROFILE,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.EDIT_PROFILE,
  ],
};

export const NAV_PERMISSIONS: Record<string, string> = {
  DASHBOARD: PERMISSIONS.VIEW_DASHBOARD,
  RESOURCES: PERMISSIONS.VIEW_RESOURCES,
  MEETING_SERVICE: PERMISSIONS.VIEW_MEETING_SERVICE,
  APPROVAL_CENTER: PERMISSIONS.VIEW_APPROVAL_CENTER,
  PROFILE: PERMISSIONS.VIEW_PROFILE,
};

export const MENU_PERMISSIONS: Record<string, string> = {
  BOOKINGS: PERMISSIONS.VIEW_BOOKINGS,
  PROFILE_EDIT: PERMISSIONS.EDIT_PROFILE,
  USERS: PERMISSIONS.MANAGE_USERS,
  ROLES: PERMISSIONS.MANAGE_ROLES,
  DEPARTMENTS: PERMISSIONS.MANAGE_DEPARTMENTS,
  RESOURCES_MANAGE: PERMISSIONS.MANAGE_RESOURCES,
  WORKFLOW_CONFIG: PERMISSIONS.CONFIG_WORKFLOW,
  DATA_CENTER: PERMISSIONS.ACCESS_DATA_CENTER,
};
